###
curl 'https://gwzjsxzbqwybnifecbqc.supabase.co/rest/v1/Tunjangan_id?select=*' \
-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3empzeHpicXd5Ym5pZmVjYnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODM1NjM5MDEsImV4cCI6MTk5OTEzOTkwMX0.EnTPswGNuKDKuAQqRlSu8mcaSBnUNAnZxTbCdG-Pchs" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3empzeHpicXd5Ym5pZmVjYnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODM1NjM5MDEsImV4cCI6MTk5OTEzOTkwMX0.EnTPswGNuKDKuAQqRlSu8mcaSBnUNAnZxTbCdG-Pchs"